CREATE TABLE IF NOT EXISTS USER
(
    ID          INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID      VARCHAR(64),
    PASSWORD    VARCHAR(64),
    NAME        VARCHAR(64),
    BIRTHDAY    DATE,
    SEX         VARCHAR(20),
    EMAIL       VARCHAR(64),
    PHONE_NUMBER VARCHAR(64),
    INTEREST    VARCHAR(256)
);