CREATE TABLE IF NOT EXISTS USER
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    USERID      VARCHAR(64),
    PASSWORD    VARCHAR(64),
    NAME        VARCHAR(64),
    BIRTHDAY    DATE,
    SEX         VARCHAR(20),
    EMAIL       VARCHAR(64),
    PHONENUMBER VARCHAR(64),
    INTEREST    VARCHAR(256)
);